language: node_js
node_js:
  - stable
cache:
  yarn: true
  directories:
    - node_modules
env:
  - CI=false
script:
  - yarn run lint
  - yarn run build
deploy:
  provider: heroku
  api_key:
    secure: lUmQnhZHJNA8qVP5imUiV1/4u9Fjwqn3mvv37bphbxMYj16RMOI7SqVNWkYkS4vqdQM3QH+NH/H3douiOYkSnHKSBgvlVnCuM/F8WiOAxcK7ZuiMfwlolJOMch+sQuUAz+ffQt0+fEkAfZ4pTLIQli/FpBfjV5Vh8PknHU9L3iDiXsEs2w1Httj24kYysg92TU2PasYmRNhfkibSX81cPhhtKS69HmVXrQqIyYqmAVHXdEKHXbZcC7paJpB3JII4jWBSV4kElLdSTJIsrmdiJBseZ2fWHKJ6RdSf2bS+5J5AG9s6balV6c8dmu0jIH5yaM0ShQeB9cc5QiDn/kXANkTXZotem4hd371buCkwMZAGAg5OY7M9emztTDJGVFMH8dSGEENM6vhLf9Vnai5YRgZ8VKWeY7SxktiEqyMvPqBLkei0UhVTalQcojSx1Da1IOMhRSaEE670VmCvRsl0ILiehOqoX09mrQHQS8gHfwAYJ8kFxbhPZLL8OpeZgtqQr2ATIecZBn4RKEKAlWJG2Zah6PBCA7vE6vezUaPOsrd2FS6HjThSdsmL1zOM9lKPrJHWUFdskD0grJ0trlXb6Rz8jlQLyIQjuCXQg9CjHxLCUNPBVMdptqsh6Ze7ZFjtcGhUYcLq9QDzSCieQ3AwOyPBdy139i/4hW1x94wJ+7E=
  app: osd-sidekick-frontend
